### ISSUE TITLE
Fig. 3 (b): definition of average number of correct boxes 

### ISSUE THREAD

**Issue by vadimkantorov** [machengcheng2016/CrossRectify-SSOD#4]
How exactly is this quantity defined? Is average taken over the batch size? Or is sum taken over the batch size?

Thanks!

**Comment by machengcheng2016** [comment]
sum taken over the batch size.

**Comment by vadimkantorov** [comment]
I see, so to get the number of correct boxes per image, need to divide by batch size. What was the batch size in this experiment? Thanks!

**Comment by machengcheng2016** [comment]
32, same with CSD/ISD.
Note that labeled images + unlabeled images = 32, which means the unlabeled data is less than 32. Please check their [data loader](https://github.com/soo89/ISD-SSD/blob/master/data/voc07_consistency.py).
