### ISSUE TITLE
训练一个轮次就停止

### ISSUE THREAD

**Issue by manongXT** [machengcheng2016/CrossRectify-SSOD#9]
使用“CUDA_VISIBLE_DEVICES=3 python3 train_ssd.py --save_interval 12000”训练时，只训练了一轮就停止，也没报错，请问是啥原因？结果显示如下：
@yunxuan01:~/CrossRectify-SSOD/SSD300$ CUDA_VISIBLE_DEVICES=0,3 python3 train_ssd.py
Loading base network...
Initializing weights...
random seed is set as 123
Loading the dataset...
Training SSD on: VOC300
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=4, cuda=True, dataset='VOC300', dataset_root='/CrossRectify-SSOD/Data/voc/VOCdevkit', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', save_interval=12000, seed=123, sup_aug_type='default', weight_decay=0.0005)
iter 0 || loss: 30.9676, loss_c: 27.1707, loss_l: 3.7969, super_len: 1

**Comment by machengcheng2016** [comment]
SSD的问题，SSD训练不稳定，多重启几次试试

**Comment by manongXT** [comment]
您好，我这边又遇到一个问题，在执行train_pseudo39.py脚本时，336行的priors_single = torch.load("priors.pt")无法执行，这个“priors.pt"该怎样加载？

**Comment by machengcheng2016** [comment]
它在[这里](https://github.com/machengcheng2016/CrossRectify-SSOD/blob/main/SSD300/priors.pt)

**Comment by manongXT** [comment]
还是无法运行，直接结束，debug的话就是卡在这一行一直不动。
